name: ' '
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:
    required: true 
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'green'
